/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  GasLimiter,
  GasLimiterInterface,
} from "../../../contracts/SecurityModules.sol/GasLimiter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "length",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxLength",
        type: "uint256",
      },
    ],
    name: "ArrayTooLarge",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "iterations",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxIterations",
        type: "uint256",
      },
    ],
    name: "TooManyIterations",
    type: "error",
  },
] as const;

export class GasLimiter__factory {
  static readonly abi = _abi;
  static createInterface(): GasLimiterInterface {
    return new Interface(_abi) as GasLimiterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): GasLimiter {
    return new Contract(address, _abi, runner) as unknown as GasLimiter;
  }
}
