/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RateLimiter,
  RateLimiterInterface,
} from "../../../contracts/SecurityModules.sol/RateLimiter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes4",
        name: "selector",
        type: "bytes4",
      },
      {
        internalType: "uint256",
        name: "resetTime",
        type: "uint256",
      },
    ],
    name: "RateLimitExceeded",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes4",
        name: "selector",
        type: "bytes4",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "window",
        type: "uint256",
      },
    ],
    name: "RateLimitConfigured",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes4",
        name: "selector",
        type: "bytes4",
      },
    ],
    name: "getRateLimitStatus",
    outputs: [
      {
        internalType: "uint256",
        name: "count",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "resetTime",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class RateLimiter__factory {
  static readonly abi = _abi;
  static createInterface(): RateLimiterInterface {
    return new Interface(_abi) as RateLimiterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): RateLimiter {
    return new Contract(address, _abi, runner) as unknown as RateLimiter;
  }
}
