/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PrivateIoTDataInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CALLBACK_TIMEOUT"
      | "addOperator"
      | "adminRefund"
      | "authorizedOperators"
      | "claimTimeoutRefund"
      | "dataRecordCount"
      | "dataRecords"
      | "deactivateDevice"
      | "depositRefundPool"
      | "deviceCount"
      | "deviceIdToIndex"
      | "deviceThresholds"
      | "devices"
      | "gateway"
      | "gatewayCallback"
      | "gatewayRequests"
      | "getContractBalance"
      | "getDataRecord"
      | "getDeviceByString"
      | "getDeviceDataCount"
      | "getDeviceInfo"
      | "getGatewayRequest"
      | "getRefundPoolBalance"
      | "getTotalDataRecords"
      | "getTotalDevices"
      | "getTotalRequests"
      | "isThresholdSet"
      | "owner"
      | "pause"
      | "paused"
      | "pauser"
      | "priceObfuscations"
      | "processThresholdAlert"
      | "refundPool"
      | "registerDevice"
      | "removeOperator"
      | "requestCount"
      | "setGateway"
      | "setPauser"
      | "setThreshold"
      | "submitDataWithCallback"
      | "unpause"
      | "userRefunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AlertTriggered"
      | "ContractPaused"
      | "ContractUnpaused"
      | "DataSubmitted"
      | "DeviceRegistered"
      | "GatewayCallbackCompleted"
      | "GatewayRequestCreated"
      | "GatewayUpdated"
      | "OperatorAdded"
      | "OperatorRemoved"
      | "PauserSet"
      | "PriceObfuscated"
      | "RefundPoolDeposited"
      | "RequestRefunded"
      | "ThresholdSet"
      | "TimeoutRefundClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CALLBACK_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTimeoutRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dataRecordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dataRecords",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateDevice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositRefundPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deviceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deviceIdToIndex",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deviceThresholds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "devices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gatewayCallback",
    values: [BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "gatewayRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDataRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeviceByString",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeviceDataCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeviceInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGatewayRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRefundPoolBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDataRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDevices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isThresholdSet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pauser", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceObfuscations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processThresholdAlert",
    values: [BigNumberish, boolean, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "refundPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerDevice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGateway",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setThreshold",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDataWithCallback",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userRefunds",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CALLBACK_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTimeoutRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRefundPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceIdToIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "devices", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gatewayCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gatewayRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDataRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeviceByString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeviceDataCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeviceInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGatewayRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRefundPoolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDataRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDevices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isThresholdSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceObfuscations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processThresholdAlert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refundPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGateway", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDataWithCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userRefunds",
    data: BytesLike
  ): Result;
}

export namespace AlertTriggeredEvent {
  export type InputTuple = [
    deviceIndex: BigNumberish,
    dataType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    deviceIndex: bigint,
    dataType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    deviceIndex: bigint;
    dataType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractPausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUnpausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataSubmittedEvent {
  export type InputTuple = [
    deviceIndex: BigNumberish,
    recordId: BigNumberish,
    dataType: BigNumberish
  ];
  export type OutputTuple = [
    deviceIndex: bigint,
    recordId: bigint,
    dataType: bigint
  ];
  export interface OutputObject {
    deviceIndex: bigint;
    recordId: bigint;
    dataType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceRegisteredEvent {
  export type InputTuple = [
    deviceIndex: BigNumberish,
    deviceId: string,
    owner: AddressLike
  ];
  export type OutputTuple = [
    deviceIndex: bigint,
    deviceId: string,
    owner: string
  ];
  export interface OutputObject {
    deviceIndex: bigint;
    deviceId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GatewayCallbackCompletedEvent {
  export type InputTuple = [requestId: BigNumberish, success: boolean];
  export type OutputTuple = [requestId: bigint, success: boolean];
  export interface OutputObject {
    requestId: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GatewayRequestCreatedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requester: AddressLike,
    deviceIndex: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    requester: string,
    deviceIndex: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
    deviceIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GatewayUpdatedEvent {
  export type InputTuple = [oldGateway: AddressLike, newGateway: AddressLike];
  export type OutputTuple = [oldGateway: string, newGateway: string];
  export interface OutputObject {
    oldGateway: string;
    newGateway: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorAddedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorRemovedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserSetEvent {
  export type InputTuple = [oldPauser: AddressLike, newPauser: AddressLike];
  export type OutputTuple = [oldPauser: string, newPauser: string];
  export interface OutputObject {
    oldPauser: string;
    newPauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceObfuscatedEvent {
  export type InputTuple = [requestId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [requestId: bigint, timestamp: bigint];
  export interface OutputObject {
    requestId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundPoolDepositedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestRefundedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [requestId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    requestId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdSetEvent {
  export type InputTuple = [deviceIndex: BigNumberish, dataType: BigNumberish];
  export type OutputTuple = [deviceIndex: bigint, dataType: bigint];
  export interface OutputObject {
    deviceIndex: bigint;
    dataType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeoutRefundClaimedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [requestId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    requestId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateIoTData extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateIoTData;
  waitForDeployment(): Promise<this>;

  interface: PrivateIoTDataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CALLBACK_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  addOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  adminRefund: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizedOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  claimTimeoutRefund: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  dataRecordCount: TypedContractMethod<[], [bigint], "view">;

  dataRecords: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, boolean] & {
        deviceIndex: bigint;
        encryptedValue: string;
        dataType: bigint;
        timestamp: bigint;
        submitter: string;
        validated: boolean;
      }
    ],
    "view"
  >;

  deactivateDevice: TypedContractMethod<
    [deviceIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositRefundPool: TypedContractMethod<[], [void], "payable">;

  deviceCount: TypedContractMethod<[], [bigint], "view">;

  deviceIdToIndex: TypedContractMethod<[arg0: string], [bigint], "view">;

  deviceThresholds: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, boolean] & {
        minValue: string;
        maxValue: string;
        isSet: boolean;
      }
    ],
    "view"
  >;

  devices: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, string, bigint, bigint] & {
        deviceId: string;
        deviceOwner: string;
        isActive: boolean;
        registrationTime: bigint;
        lastDataValue: string;
        lastUpdateTime: bigint;
        dataSubmissionCount: bigint;
      }
    ],
    "view"
  >;

  gateway: TypedContractMethod<[], [string], "view">;

  gatewayCallback: TypedContractMethod<
    [
      requestId: BigNumberish,
      decryptedValue: BigNumberish,
      signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  gatewayRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        requestId: bigint;
        requester: string;
        deviceIndex: bigint;
        dataType: bigint;
        encryptedValue: string;
        timestamp: bigint;
        timeout: bigint;
        completed: boolean;
        refunded: boolean;
        depositAmount: bigint;
      }
    ],
    "view"
  >;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getDataRecord: TypedContractMethod<
    [recordId: BigNumberish],
    [
      [bigint, bigint, bigint, string, boolean] & {
        deviceIndex: bigint;
        dataType: bigint;
        timestamp: bigint;
        submitter: string;
        validated: boolean;
      }
    ],
    "view"
  >;

  getDeviceByString: TypedContractMethod<
    [deviceId: string],
    [[bigint, boolean] & { deviceIndex: bigint; exists: boolean }],
    "view"
  >;

  getDeviceDataCount: TypedContractMethod<
    [deviceIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getDeviceInfo: TypedContractMethod<
    [deviceIndex: BigNumberish],
    [
      [string, string, boolean, bigint, bigint, bigint] & {
        deviceId: string;
        deviceOwner: string;
        isActive: boolean;
        registrationTime: bigint;
        lastUpdateTime: bigint;
        dataSubmissionCount: bigint;
      }
    ],
    "view"
  >;

  getGatewayRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        requester: string;
        deviceIndex: bigint;
        dataType: bigint;
        timestamp: bigint;
        timeout: bigint;
        completed: boolean;
        refunded: boolean;
        depositAmount: bigint;
      }
    ],
    "view"
  >;

  getRefundPoolBalance: TypedContractMethod<[], [bigint], "view">;

  getTotalDataRecords: TypedContractMethod<[], [bigint], "view">;

  getTotalDevices: TypedContractMethod<[], [bigint], "view">;

  getTotalRequests: TypedContractMethod<[], [bigint], "view">;

  isThresholdSet: TypedContractMethod<
    [deviceIndex: BigNumberish, dataType: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pauser: TypedContractMethod<[], [string], "view">;

  priceObfuscations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        randomMultiplier: string;
        obfuscatedPrice: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  processThresholdAlert: TypedContractMethod<
    [requestId: BigNumberish, shouldAlert: boolean, signatures: BytesLike[]],
    [void],
    "nonpayable"
  >;

  refundPool: TypedContractMethod<[], [bigint], "view">;

  registerDevice: TypedContractMethod<
    [deviceId: string],
    [bigint],
    "nonpayable"
  >;

  removeOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  requestCount: TypedContractMethod<[], [bigint], "view">;

  setGateway: TypedContractMethod<
    [_gateway: AddressLike],
    [void],
    "nonpayable"
  >;

  setPauser: TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;

  setThreshold: TypedContractMethod<
    [
      deviceIndex: BigNumberish,
      dataType: BigNumberish,
      minValue: BigNumberish,
      maxValue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitDataWithCallback: TypedContractMethod<
    [deviceIndex: BigNumberish, value: BigNumberish, dataType: BigNumberish],
    [bigint],
    "payable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userRefunds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CALLBACK_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminRefund"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimTimeoutRefund"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dataRecordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dataRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, boolean] & {
        deviceIndex: bigint;
        encryptedValue: string;
        dataType: bigint;
        timestamp: bigint;
        submitter: string;
        validated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateDevice"
  ): TypedContractMethod<[deviceIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositRefundPool"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "deviceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deviceIdToIndex"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "deviceThresholds"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, boolean] & {
        minValue: string;
        maxValue: string;
        isSet: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "devices"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, string, bigint, bigint] & {
        deviceId: string;
        deviceOwner: string;
        isActive: boolean;
        registrationTime: bigint;
        lastDataValue: string;
        lastUpdateTime: bigint;
        dataSubmissionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "gateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gatewayCallback"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      decryptedValue: BigNumberish,
      signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gatewayRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        requestId: bigint;
        requester: string;
        deviceIndex: bigint;
        dataType: bigint;
        encryptedValue: string;
        timestamp: bigint;
        timeout: bigint;
        completed: boolean;
        refunded: boolean;
        depositAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDataRecord"
  ): TypedContractMethod<
    [recordId: BigNumberish],
    [
      [bigint, bigint, bigint, string, boolean] & {
        deviceIndex: bigint;
        dataType: bigint;
        timestamp: bigint;
        submitter: string;
        validated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeviceByString"
  ): TypedContractMethod<
    [deviceId: string],
    [[bigint, boolean] & { deviceIndex: bigint; exists: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeviceDataCount"
  ): TypedContractMethod<[deviceIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDeviceInfo"
  ): TypedContractMethod<
    [deviceIndex: BigNumberish],
    [
      [string, string, boolean, bigint, bigint, bigint] & {
        deviceId: string;
        deviceOwner: string;
        isActive: boolean;
        registrationTime: bigint;
        lastUpdateTime: bigint;
        dataSubmissionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGatewayRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        requester: string;
        deviceIndex: bigint;
        dataType: bigint;
        timestamp: bigint;
        timeout: bigint;
        completed: boolean;
        refunded: boolean;
        depositAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRefundPoolBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalDataRecords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalDevices"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalRequests"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isThresholdSet"
  ): TypedContractMethod<
    [deviceIndex: BigNumberish, dataType: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pauser"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceObfuscations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        randomMultiplier: string;
        obfuscatedPrice: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "processThresholdAlert"
  ): TypedContractMethod<
    [requestId: BigNumberish, shouldAlert: boolean, signatures: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refundPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerDevice"
  ): TypedContractMethod<[deviceId: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setGateway"
  ): TypedContractMethod<[_gateway: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setThreshold"
  ): TypedContractMethod<
    [
      deviceIndex: BigNumberish,
      dataType: BigNumberish,
      minValue: BigNumberish,
      maxValue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitDataWithCallback"
  ): TypedContractMethod<
    [deviceIndex: BigNumberish, value: BigNumberish, dataType: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userRefunds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "AlertTriggered"
  ): TypedContractEvent<
    AlertTriggeredEvent.InputTuple,
    AlertTriggeredEvent.OutputTuple,
    AlertTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "ContractPaused"
  ): TypedContractEvent<
    ContractPausedEvent.InputTuple,
    ContractPausedEvent.OutputTuple,
    ContractPausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUnpaused"
  ): TypedContractEvent<
    ContractUnpausedEvent.InputTuple,
    ContractUnpausedEvent.OutputTuple,
    ContractUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "DataSubmitted"
  ): TypedContractEvent<
    DataSubmittedEvent.InputTuple,
    DataSubmittedEvent.OutputTuple,
    DataSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DeviceRegistered"
  ): TypedContractEvent<
    DeviceRegisteredEvent.InputTuple,
    DeviceRegisteredEvent.OutputTuple,
    DeviceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "GatewayCallbackCompleted"
  ): TypedContractEvent<
    GatewayCallbackCompletedEvent.InputTuple,
    GatewayCallbackCompletedEvent.OutputTuple,
    GatewayCallbackCompletedEvent.OutputObject
  >;
  getEvent(
    key: "GatewayRequestCreated"
  ): TypedContractEvent<
    GatewayRequestCreatedEvent.InputTuple,
    GatewayRequestCreatedEvent.OutputTuple,
    GatewayRequestCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GatewayUpdated"
  ): TypedContractEvent<
    GatewayUpdatedEvent.InputTuple,
    GatewayUpdatedEvent.OutputTuple,
    GatewayUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorAdded"
  ): TypedContractEvent<
    OperatorAddedEvent.InputTuple,
    OperatorAddedEvent.OutputTuple,
    OperatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorRemoved"
  ): TypedContractEvent<
    OperatorRemovedEvent.InputTuple,
    OperatorRemovedEvent.OutputTuple,
    OperatorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "PauserSet"
  ): TypedContractEvent<
    PauserSetEvent.InputTuple,
    PauserSetEvent.OutputTuple,
    PauserSetEvent.OutputObject
  >;
  getEvent(
    key: "PriceObfuscated"
  ): TypedContractEvent<
    PriceObfuscatedEvent.InputTuple,
    PriceObfuscatedEvent.OutputTuple,
    PriceObfuscatedEvent.OutputObject
  >;
  getEvent(
    key: "RefundPoolDeposited"
  ): TypedContractEvent<
    RefundPoolDepositedEvent.InputTuple,
    RefundPoolDepositedEvent.OutputTuple,
    RefundPoolDepositedEvent.OutputObject
  >;
  getEvent(
    key: "RequestRefunded"
  ): TypedContractEvent<
    RequestRefundedEvent.InputTuple,
    RequestRefundedEvent.OutputTuple,
    RequestRefundedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdSet"
  ): TypedContractEvent<
    ThresholdSetEvent.InputTuple,
    ThresholdSetEvent.OutputTuple,
    ThresholdSetEvent.OutputObject
  >;
  getEvent(
    key: "TimeoutRefundClaimed"
  ): TypedContractEvent<
    TimeoutRefundClaimedEvent.InputTuple,
    TimeoutRefundClaimedEvent.OutputTuple,
    TimeoutRefundClaimedEvent.OutputObject
  >;

  filters: {
    "AlertTriggered(uint256,uint8,uint256)": TypedContractEvent<
      AlertTriggeredEvent.InputTuple,
      AlertTriggeredEvent.OutputTuple,
      AlertTriggeredEvent.OutputObject
    >;
    AlertTriggered: TypedContractEvent<
      AlertTriggeredEvent.InputTuple,
      AlertTriggeredEvent.OutputTuple,
      AlertTriggeredEvent.OutputObject
    >;

    "ContractPaused(address)": TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;
    ContractPaused: TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;

    "ContractUnpaused(address)": TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;
    ContractUnpaused: TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;

    "DataSubmitted(uint256,uint256,uint8)": TypedContractEvent<
      DataSubmittedEvent.InputTuple,
      DataSubmittedEvent.OutputTuple,
      DataSubmittedEvent.OutputObject
    >;
    DataSubmitted: TypedContractEvent<
      DataSubmittedEvent.InputTuple,
      DataSubmittedEvent.OutputTuple,
      DataSubmittedEvent.OutputObject
    >;

    "DeviceRegistered(uint256,string,address)": TypedContractEvent<
      DeviceRegisteredEvent.InputTuple,
      DeviceRegisteredEvent.OutputTuple,
      DeviceRegisteredEvent.OutputObject
    >;
    DeviceRegistered: TypedContractEvent<
      DeviceRegisteredEvent.InputTuple,
      DeviceRegisteredEvent.OutputTuple,
      DeviceRegisteredEvent.OutputObject
    >;

    "GatewayCallbackCompleted(uint256,bool)": TypedContractEvent<
      GatewayCallbackCompletedEvent.InputTuple,
      GatewayCallbackCompletedEvent.OutputTuple,
      GatewayCallbackCompletedEvent.OutputObject
    >;
    GatewayCallbackCompleted: TypedContractEvent<
      GatewayCallbackCompletedEvent.InputTuple,
      GatewayCallbackCompletedEvent.OutputTuple,
      GatewayCallbackCompletedEvent.OutputObject
    >;

    "GatewayRequestCreated(uint256,address,uint256)": TypedContractEvent<
      GatewayRequestCreatedEvent.InputTuple,
      GatewayRequestCreatedEvent.OutputTuple,
      GatewayRequestCreatedEvent.OutputObject
    >;
    GatewayRequestCreated: TypedContractEvent<
      GatewayRequestCreatedEvent.InputTuple,
      GatewayRequestCreatedEvent.OutputTuple,
      GatewayRequestCreatedEvent.OutputObject
    >;

    "GatewayUpdated(address,address)": TypedContractEvent<
      GatewayUpdatedEvent.InputTuple,
      GatewayUpdatedEvent.OutputTuple,
      GatewayUpdatedEvent.OutputObject
    >;
    GatewayUpdated: TypedContractEvent<
      GatewayUpdatedEvent.InputTuple,
      GatewayUpdatedEvent.OutputTuple,
      GatewayUpdatedEvent.OutputObject
    >;

    "OperatorAdded(address)": TypedContractEvent<
      OperatorAddedEvent.InputTuple,
      OperatorAddedEvent.OutputTuple,
      OperatorAddedEvent.OutputObject
    >;
    OperatorAdded: TypedContractEvent<
      OperatorAddedEvent.InputTuple,
      OperatorAddedEvent.OutputTuple,
      OperatorAddedEvent.OutputObject
    >;

    "OperatorRemoved(address)": TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;
    OperatorRemoved: TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;

    "PauserSet(address,address)": TypedContractEvent<
      PauserSetEvent.InputTuple,
      PauserSetEvent.OutputTuple,
      PauserSetEvent.OutputObject
    >;
    PauserSet: TypedContractEvent<
      PauserSetEvent.InputTuple,
      PauserSetEvent.OutputTuple,
      PauserSetEvent.OutputObject
    >;

    "PriceObfuscated(uint256,uint256)": TypedContractEvent<
      PriceObfuscatedEvent.InputTuple,
      PriceObfuscatedEvent.OutputTuple,
      PriceObfuscatedEvent.OutputObject
    >;
    PriceObfuscated: TypedContractEvent<
      PriceObfuscatedEvent.InputTuple,
      PriceObfuscatedEvent.OutputTuple,
      PriceObfuscatedEvent.OutputObject
    >;

    "RefundPoolDeposited(uint256)": TypedContractEvent<
      RefundPoolDepositedEvent.InputTuple,
      RefundPoolDepositedEvent.OutputTuple,
      RefundPoolDepositedEvent.OutputObject
    >;
    RefundPoolDeposited: TypedContractEvent<
      RefundPoolDepositedEvent.InputTuple,
      RefundPoolDepositedEvent.OutputTuple,
      RefundPoolDepositedEvent.OutputObject
    >;

    "RequestRefunded(uint256,address,uint256)": TypedContractEvent<
      RequestRefundedEvent.InputTuple,
      RequestRefundedEvent.OutputTuple,
      RequestRefundedEvent.OutputObject
    >;
    RequestRefunded: TypedContractEvent<
      RequestRefundedEvent.InputTuple,
      RequestRefundedEvent.OutputTuple,
      RequestRefundedEvent.OutputObject
    >;

    "ThresholdSet(uint256,uint8)": TypedContractEvent<
      ThresholdSetEvent.InputTuple,
      ThresholdSetEvent.OutputTuple,
      ThresholdSetEvent.OutputObject
    >;
    ThresholdSet: TypedContractEvent<
      ThresholdSetEvent.InputTuple,
      ThresholdSetEvent.OutputTuple,
      ThresholdSetEvent.OutputObject
    >;

    "TimeoutRefundClaimed(uint256,address,uint256)": TypedContractEvent<
      TimeoutRefundClaimedEvent.InputTuple,
      TimeoutRefundClaimedEvent.OutputTuple,
      TimeoutRefundClaimedEvent.OutputObject
    >;
    TimeoutRefundClaimed: TypedContractEvent<
      TimeoutRefundClaimedEvent.InputTuple,
      TimeoutRefundClaimedEvent.OutputTuple,
      TimeoutRefundClaimedEvent.OutputObject
    >;
  };
}
