/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as privateIoTDataAdvancedSol from "./PrivateIoTDataAdvanced.sol";
export type { privateIoTDataAdvancedSol };
import type * as securityModulesSol from "./SecurityModules.sol";
export type { securityModulesSol };
export type { PrivateIoTData } from "./PrivateIoTData";
