/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateIoTDataInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOperator"
      | "authorizedOperators"
      | "dataRecordCount"
      | "dataRecords"
      | "deactivateDevice"
      | "deviceCount"
      | "deviceIdToIndex"
      | "deviceThresholds"
      | "devices"
      | "getDataRecord"
      | "getDeviceByString"
      | "getDeviceDataCount"
      | "getDeviceInfo"
      | "getTotalDataRecords"
      | "getTotalDevices"
      | "isThresholdSet"
      | "owner"
      | "processThresholdAlert"
      | "registerDevice"
      | "removeOperator"
      | "setThreshold"
      | "submitData"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AlertTriggered"
      | "DataSubmitted"
      | "DeviceRegistered"
      | "OperatorAdded"
      | "OperatorRemoved"
      | "ThresholdSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dataRecordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dataRecords",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateDevice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deviceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deviceIdToIndex",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deviceThresholds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "devices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDataRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeviceByString",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeviceDataCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeviceInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDataRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDevices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isThresholdSet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processThresholdAlert",
    values: [BigNumberish, boolean, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDevice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setThreshold",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitData",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceIdToIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "devices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDataRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeviceByString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeviceDataCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeviceInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDataRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDevices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isThresholdSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processThresholdAlert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitData", data: BytesLike): Result;
}

export namespace AlertTriggeredEvent {
  export type InputTuple = [
    deviceIndex: BigNumberish,
    dataType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    deviceIndex: bigint,
    dataType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    deviceIndex: bigint;
    dataType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataSubmittedEvent {
  export type InputTuple = [
    deviceIndex: BigNumberish,
    recordId: BigNumberish,
    dataType: BigNumberish
  ];
  export type OutputTuple = [
    deviceIndex: bigint,
    recordId: bigint,
    dataType: bigint
  ];
  export interface OutputObject {
    deviceIndex: bigint;
    recordId: bigint;
    dataType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceRegisteredEvent {
  export type InputTuple = [
    deviceIndex: BigNumberish,
    deviceId: string,
    owner: AddressLike
  ];
  export type OutputTuple = [
    deviceIndex: bigint,
    deviceId: string,
    owner: string
  ];
  export interface OutputObject {
    deviceIndex: bigint;
    deviceId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorAddedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorRemovedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdSetEvent {
  export type InputTuple = [deviceIndex: BigNumberish, dataType: BigNumberish];
  export type OutputTuple = [deviceIndex: bigint, dataType: bigint];
  export interface OutputObject {
    deviceIndex: bigint;
    dataType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateIoTData extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateIoTData;
  waitForDeployment(): Promise<this>;

  interface: PrivateIoTDataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  dataRecordCount: TypedContractMethod<[], [bigint], "view">;

  dataRecords: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        deviceIndex: bigint;
        encryptedValue: string;
        dataType: bigint;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  deactivateDevice: TypedContractMethod<
    [deviceIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  deviceCount: TypedContractMethod<[], [bigint], "view">;

  deviceIdToIndex: TypedContractMethod<[arg0: string], [bigint], "view">;

  deviceThresholds: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, boolean] & {
        minValue: string;
        maxValue: string;
        isSet: boolean;
      }
    ],
    "view"
  >;

  devices: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, string, bigint] & {
        deviceId: string;
        deviceOwner: string;
        isActive: boolean;
        registrationTime: bigint;
        lastDataValue: string;
        lastUpdateTime: bigint;
      }
    ],
    "view"
  >;

  getDataRecord: TypedContractMethod<
    [recordId: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        deviceIndex: bigint;
        dataType: bigint;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  getDeviceByString: TypedContractMethod<
    [deviceId: string],
    [[bigint, boolean] & { deviceIndex: bigint; exists: boolean }],
    "view"
  >;

  getDeviceDataCount: TypedContractMethod<
    [deviceIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getDeviceInfo: TypedContractMethod<
    [deviceIndex: BigNumberish],
    [
      [string, string, boolean, bigint, bigint] & {
        deviceId: string;
        deviceOwner: string;
        isActive: boolean;
        registrationTime: bigint;
        lastUpdateTime: bigint;
      }
    ],
    "view"
  >;

  getTotalDataRecords: TypedContractMethod<[], [bigint], "view">;

  getTotalDevices: TypedContractMethod<[], [bigint], "view">;

  isThresholdSet: TypedContractMethod<
    [deviceIndex: BigNumberish, dataType: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processThresholdAlert: TypedContractMethod<
    [requestId: BigNumberish, shouldAlert: boolean, signatures: BytesLike[]],
    [void],
    "nonpayable"
  >;

  registerDevice: TypedContractMethod<
    [deviceId: string],
    [bigint],
    "nonpayable"
  >;

  removeOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  setThreshold: TypedContractMethod<
    [
      deviceIndex: BigNumberish,
      dataType: BigNumberish,
      minValue: BigNumberish,
      maxValue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitData: TypedContractMethod<
    [deviceIndex: BigNumberish, value: BigNumberish, dataType: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "dataRecordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dataRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        deviceIndex: bigint;
        encryptedValue: string;
        dataType: bigint;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateDevice"
  ): TypedContractMethod<[deviceIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deviceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deviceIdToIndex"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "deviceThresholds"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, boolean] & {
        minValue: string;
        maxValue: string;
        isSet: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "devices"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, string, bigint] & {
        deviceId: string;
        deviceOwner: string;
        isActive: boolean;
        registrationTime: bigint;
        lastDataValue: string;
        lastUpdateTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDataRecord"
  ): TypedContractMethod<
    [recordId: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        deviceIndex: bigint;
        dataType: bigint;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeviceByString"
  ): TypedContractMethod<
    [deviceId: string],
    [[bigint, boolean] & { deviceIndex: bigint; exists: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeviceDataCount"
  ): TypedContractMethod<[deviceIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDeviceInfo"
  ): TypedContractMethod<
    [deviceIndex: BigNumberish],
    [
      [string, string, boolean, bigint, bigint] & {
        deviceId: string;
        deviceOwner: string;
        isActive: boolean;
        registrationTime: bigint;
        lastUpdateTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalDataRecords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalDevices"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isThresholdSet"
  ): TypedContractMethod<
    [deviceIndex: BigNumberish, dataType: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processThresholdAlert"
  ): TypedContractMethod<
    [requestId: BigNumberish, shouldAlert: boolean, signatures: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerDevice"
  ): TypedContractMethod<[deviceId: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setThreshold"
  ): TypedContractMethod<
    [
      deviceIndex: BigNumberish,
      dataType: BigNumberish,
      minValue: BigNumberish,
      maxValue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitData"
  ): TypedContractMethod<
    [deviceIndex: BigNumberish, value: BigNumberish, dataType: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AlertTriggered"
  ): TypedContractEvent<
    AlertTriggeredEvent.InputTuple,
    AlertTriggeredEvent.OutputTuple,
    AlertTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "DataSubmitted"
  ): TypedContractEvent<
    DataSubmittedEvent.InputTuple,
    DataSubmittedEvent.OutputTuple,
    DataSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DeviceRegistered"
  ): TypedContractEvent<
    DeviceRegisteredEvent.InputTuple,
    DeviceRegisteredEvent.OutputTuple,
    DeviceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OperatorAdded"
  ): TypedContractEvent<
    OperatorAddedEvent.InputTuple,
    OperatorAddedEvent.OutputTuple,
    OperatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorRemoved"
  ): TypedContractEvent<
    OperatorRemovedEvent.InputTuple,
    OperatorRemovedEvent.OutputTuple,
    OperatorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdSet"
  ): TypedContractEvent<
    ThresholdSetEvent.InputTuple,
    ThresholdSetEvent.OutputTuple,
    ThresholdSetEvent.OutputObject
  >;

  filters: {
    "AlertTriggered(uint256,uint8,uint256)": TypedContractEvent<
      AlertTriggeredEvent.InputTuple,
      AlertTriggeredEvent.OutputTuple,
      AlertTriggeredEvent.OutputObject
    >;
    AlertTriggered: TypedContractEvent<
      AlertTriggeredEvent.InputTuple,
      AlertTriggeredEvent.OutputTuple,
      AlertTriggeredEvent.OutputObject
    >;

    "DataSubmitted(uint256,uint256,uint8)": TypedContractEvent<
      DataSubmittedEvent.InputTuple,
      DataSubmittedEvent.OutputTuple,
      DataSubmittedEvent.OutputObject
    >;
    DataSubmitted: TypedContractEvent<
      DataSubmittedEvent.InputTuple,
      DataSubmittedEvent.OutputTuple,
      DataSubmittedEvent.OutputObject
    >;

    "DeviceRegistered(uint256,string,address)": TypedContractEvent<
      DeviceRegisteredEvent.InputTuple,
      DeviceRegisteredEvent.OutputTuple,
      DeviceRegisteredEvent.OutputObject
    >;
    DeviceRegistered: TypedContractEvent<
      DeviceRegisteredEvent.InputTuple,
      DeviceRegisteredEvent.OutputTuple,
      DeviceRegisteredEvent.OutputObject
    >;

    "OperatorAdded(address)": TypedContractEvent<
      OperatorAddedEvent.InputTuple,
      OperatorAddedEvent.OutputTuple,
      OperatorAddedEvent.OutputObject
    >;
    OperatorAdded: TypedContractEvent<
      OperatorAddedEvent.InputTuple,
      OperatorAddedEvent.OutputTuple,
      OperatorAddedEvent.OutputObject
    >;

    "OperatorRemoved(address)": TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;
    OperatorRemoved: TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;

    "ThresholdSet(uint256,uint8)": TypedContractEvent<
      ThresholdSetEvent.InputTuple,
      ThresholdSetEvent.OutputTuple,
      ThresholdSetEvent.OutputObject
    >;
    ThresholdSet: TypedContractEvent<
      ThresholdSetEvent.InputTuple,
      ThresholdSetEvent.OutputTuple,
      ThresholdSetEvent.OutputObject
    >;
  };
}
