/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RateLimiterInterface extends Interface {
  getFunction(nameOrSignature: "getRateLimitStatus"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RateLimitConfigured"): EventFragment;

  encodeFunctionData(
    functionFragment: "getRateLimitStatus",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRateLimitStatus",
    data: BytesLike
  ): Result;
}

export namespace RateLimitConfiguredEvent {
  export type InputTuple = [
    selector: BytesLike,
    limit: BigNumberish,
    window: BigNumberish
  ];
  export type OutputTuple = [selector: string, limit: bigint, window: bigint];
  export interface OutputObject {
    selector: string;
    limit: bigint;
    window: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RateLimiter extends BaseContract {
  connect(runner?: ContractRunner | null): RateLimiter;
  waitForDeployment(): Promise<this>;

  interface: RateLimiterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRateLimitStatus: TypedContractMethod<
    [user: AddressLike, selector: BytesLike],
    [
      [bigint, bigint, bigint] & {
        count: bigint;
        limit: bigint;
        resetTime: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRateLimitStatus"
  ): TypedContractMethod<
    [user: AddressLike, selector: BytesLike],
    [
      [bigint, bigint, bigint] & {
        count: bigint;
        limit: bigint;
        resetTime: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "RateLimitConfigured"
  ): TypedContractEvent<
    RateLimitConfiguredEvent.InputTuple,
    RateLimitConfiguredEvent.OutputTuple,
    RateLimitConfiguredEvent.OutputObject
  >;

  filters: {
    "RateLimitConfigured(bytes4,uint256,uint256)": TypedContractEvent<
      RateLimitConfiguredEvent.InputTuple,
      RateLimitConfiguredEvent.OutputTuple,
      RateLimitConfiguredEvent.OutputObject
    >;
    RateLimitConfigured: TypedContractEvent<
      RateLimitConfiguredEvent.InputTuple,
      RateLimitConfiguredEvent.OutputTuple,
      RateLimitConfiguredEvent.OutputObject
    >;
  };
}
